name: teoria

services:
  platform-check:
    volumes:
      - ../platform/registries:/app/platform/registries:ro
      - ../platform/references:/app/platform/references:ro

  pipelines-check:
    volumes:
      - ../pipelines/connectors:/app/pipelines/connectors:ro
      - ../pipelines/definitions:/app/pipelines/definitions:ro
      - ../pipelines/verification_cases:/app/pipelines/verification_cases:ro
      - ../pipelines/references:/app/pipelines/references:ro
      - ../platform/registries:/app/platform/registries:ro
      - ../platform/references:/app/platform/references:ro
