"""Public import surface for market-context SQL statements.

Queries live beside their functional area; readers may continue importing from
this package while processor modules are separated.
"""

from .outcomes import (
    _BID_RELATIONSHIP_NOTICE_QUERY,
    _BID_RELATIONSHIP_PARTICIPANTS_QUERY,
    _CONTRACT_SUPPLIERS_BATCH_QUERY,
    _ORGANIZATION_AWARD_CONTRACT_ACTIVITIES_QUERY,
    _ORGANIZATION_FIELD_EVENT_ROWS_QUERY,
    _PROCUREMENT_ACTIVITY_COMPANY_PARTICIPATION_QUERY,
    _PROCUREMENT_ACTIVITY_NOTICES_QUERY,
    _PROCUREMENT_OUTCOME_AWARDS_QUERY,
    _PROCUREMENT_OUTCOME_CONTRACTS_QUERY,
)
from .participation import (
    _BID_NOTICE_PARTICIPATIONS_QUERY,
    _COMPANY_COMPETITORS_QUERY,
    _COMPANY_PARTICIPATIONS_QUERY,
    _ORGANIZATION_RELATIONSHIP_ACTIVITIES_QUERY,
    _PROCUREMENT_CLASSIFICATION_HIERARCHY_QUERY,
)
from .profiles import (
    _BID_CONTEXT_COMPETITION_QUERY,
    _BID_CONTEXT_PEER_COMPETITION_QUERY,
    _BID_CONTEXT_PEER_CONTRACTS_QUERY,
    _ORGANIZATION_COMPANY_FIRST_AWARD_OR_CONTRACT_QUERY,
    _PROCUREMENT_RELATIONSHIP_CONTEXT_QUERY,
    _PROCUREMENT_PROFILE_ACTIVITIES_QUERY,
    _PROCUREMENT_PROFILE_NOTICES_QUERY,
)
from .similar_projects import (
    _COMPANY_SIMILAR_PROJECT_EXPERIENCE_QUERY,
    _COMPANY_SIMILAR_PROJECT_METRICS_QUERY,
    _COMPANY_SIMILAR_PROJECT_REFERENCE_QUERY,
    _SIMILAR_NOTICE_CANDIDATES_QUERY,
)

__all__ = [name for name in globals() if name.startswith("_") and name.endswith("_QUERY")]
